### ISSUE TITLE
Using the library, nothing is being displayed in the application.

### ISSUE THREAD

**Issue by codeahead14** [mukeshsolanki/MarkdownView-Android#2]
Hi I am trying to use the MarkdownView library and what I have observed is no matter what I do, nothing is being displayed in my layout. I have followed exactly what has been given in the example yet no text is being displayed in the application.

The links to the file where I using the MarkdownView

https://github.com/codeahead14/Working_with_Git_API/blob/Submission_v1/app/src/main/java/com/example/gaurav/gitfetchapp/Repositories/RepositoryBranchPagerFragment.java

https://github.com/codeahead14/Working_with_Git_API/blob/Submission_v1/app/src/main/res/layout/repository_branch_details_layout.xml

**Comment by mukeshsolanki** [comment]
@codeahead14 from what is see you are not using this library 😕  you seem to be using a different library

**Comment by codeahead14** [comment]
@mukeshsolanki Yeah had to change that because I did not plan to wait for 2 months for the issue resolution. Anyways, have got a better and working option.
