### ISSUE TITLE
This project is a copy of MarkedView-for-Android

### ISSUE THREAD

**Issue by GrenderG** [mukeshsolanki/MarkdownView-Android#22]
This project is a copy of [**MarkedView-for-Android**](https://github.com/mittsuu/MarkedView-for-Android), you have done the same as in [easypreferences](https://github.com/mukeshsolanki/easypreferences/issues/6). You should acknowledge @mittsuu's work.

This is not how FOSS community should behave, you are having a toxic behavior.

**Comment by mukeshsolanki** [comment]
This is not a copy of the library you are mentioning. Get your fact right before you attack anyone publicly. Look at the first commit date for both the projects. As for easyprefrence I have responded on that repo accordingly.
