### ISSUE TITLE
URL images are not being rendered

### ISSUE THREAD

**Issue by dessalines** [mukeshsolanki/MarkdownView-Android#34]
### Subject of the issue
When using jetpack compose, none of the URL images are being rendered.

### Tell us how to reproduce this issue. Please provide a working demo.
Use something like ![](URL_IMAGE) anywhere

### Expected behaviour
It should show the image

### Actual behaviour
The image isn't shown.

Could be a coil issue?

**Comment by mukeshsolanki** [comment]
Can you share some code snippet of the MD file?

**Comment by dessalines** [comment]
any image, try this: 

`![](https://i.imgur.com/6xkFbQ0.jpg)`

**Comment by mukeshsolanki** [comment]
This seems to be rendering for me. from both the sample file and using text. Here is what I'm doing

1. Created a file in the assets folder called `Sample.md`
The contents of this file is `![](https://i.imgur.com/6xkFbQ0.jpg)`

2. In the activity I'm doing
```
MarkDown(
  file = getFileFromAssets(
      context = LocalContext.current,
      fileName = "Sample.md"
  ),
  modifier = Modifier.fillMaxSize()
)
```
3. The output I'm getting is this 
![Screenshot_20220405_114121](https://user-images.githubusercontent.com/10584200/161690156-2ccb5cad-b4f1-481b-9d50-927f50e9df00.png)

**Comment by dessalines** [comment]
Is providing that LocalContext necessary for the Image fetching? That isn't referenced in the README at all.

**Comment by mukeshsolanki** [comment]
Context is not needed by the library. Im using the context for the method I created in the sample app that fetches the file from the assets folder. Are we okay to close this issue?

**Comment by dessalines** [comment]
Yep.
