### ISSUE TITLE
Images within markdown text

### ISSUE THREAD

**Issue by markfili** [mukeshsolanki/MarkdownView-Android#4]
Hi,

thank you for your library, it really helps a lot!
I have one question; how to display images inside the MarkdownView?

I've tried 
`![home](file:///android_asset/markdown/images/home.png)`
and
`![home](images/home.png)`
but I still get the `FileNotFoundException`.

Thank you in advance

**Comment by mukeshsolanki** [comment]
Images from assets cannot be load at the moment you could host the image online and use the url

**Comment by mukeshsolanki** [comment]
Images from assets cannot be load at the moment you could host the image online and use the url

**Comment by mukeshsolanki** [comment]
Images from assets cannot be load at the moment you could host the image online and use the url

**Comment by petered** [comment]
For what it's worth, this feature has my vote
