### ISSUE TITLE
Flexibility theming

### ISSUE THREAD

**Issue by Khang-NT** [mukeshsolanki/MarkdownView-Android#9]
Your library is so cool, but seem like it has static theme and dev can not customize at all. In my personal situation, I have a table with large content inside, without divider between two row or two columns, the table isn't readable, it will be better if dev can easy customize theme  without extends your library.

![Screenshoot](http://i.imgur.com/u3pkmJrl.png)

Have a look at https://github.com/falnatsheh/MarkdownView, It allows dev set theme dynamically but it can not display table at all.

**Comment by mukeshsolanki** [comment]
You can customize and apply custom themes by using html tags
